#!/usr/bin/env python3
"""
generate.py — build the publications region of index.html from papers.yml.

WORKFLOW (this is the whole point — no more copy-pasting HTML per paper):
    1. Edit  papers.yml   (add or update one short entry per paper)
    2. Run   python3 generate.py
    3. Push  (GitHub Pages serves the regenerated static index.html)

The script rewrites ONLY the block between these two markers in index.html:
    <!-- PAPERS:START (generated by generate.py - do not edit by hand) -->
    ...
    <!-- PAPERS:END -->
Everything else in index.html (About, Articles, banner, footer) is left alone.
Do not hand-edit inside the markers; your changes will be overwritten.

Requires PyYAML:  pip3 install pyyaml
"""

import html
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit(
        "ERROR: PyYAML is not installed.\n"
        "Install it once with:\n\n    pip3 install pyyaml\n"
    )

HERE = os.path.dirname(os.path.abspath(__file__))
YAML_PATH = os.path.join(HERE, "papers.yml")
HTML_PATH = os.path.join(HERE, "index.html")

START = "<!-- PAPERS:START (generated by generate.py - do not edit by hand) -->"
END = "<!-- PAPERS:END -->"

# section key -> (heading text, optional note line under the heading)
SECTIONS = [
    ("preprints", "Preprints/In Preparation",
     "(Bold denotes members of or closely associated with the Lin Lab.)"),
    ("highlighted", "Highlighted published papers", None),
    ("other", "Other published papers", None),
]


def render_author(a):
    """One author -> HTML. name required; optional link (data-link key) and emph (bold)."""
    if isinstance(a, str):
        a = {"name": a}
    name = a["name"]
    if a.get("link"):
        inner = ('<a class="link" href="" target="_blank" '
                 'data-link="{key}">{name}</a>').format(key=a["link"], name=name)
    else:
        inner = name
    if a.get("emph"):
        inner = "<span class=\"emph\">{0}</span>".format(inner)
    return inner


def render_authors(authors, note):
    """Join authors with commas, 'and' before the last one, terminal period, then note."""
    parts = [render_author(a) for a in authors]
    if len(parts) == 1:
        joined = parts[0]
    elif len(parts) == 2:
        joined = parts[0] + " and " + parts[1]
    else:
        joined = ", ".join(parts[:-1]) + ", and " + parts[-1]
    joined += "."
    if note:
        joined += " " + note
    return joined


def render_links(links):
    out = []
    for lk in links or []:
        # `raw` escape hatch: verbatim HTML for rare grouped links, e.g.
        #   {raw: "(<a ...>git 1</a>, <a ...>git 2</a>)"}
        if "raw" in lk:
            out.append(lk["raw"])
        else:
            out.append('(<a href="{url}" target="_blank">{label}</a>)'.format(
                url=lk["url"], label=lk["label"]))
    return " ".join(out)


def render_paper(p):
    required = ["id", "section", "image", "title", "authors", "pubtitle", "venue"]
    missing = [f for f in required if not p.get(f)]
    if missing:
        sys.exit("ERROR: paper '{0}' is missing required field(s): {1}".format(
            p.get("id", "?"), ", ".join(missing)))

    alt = p.get("alt") or (p["title"] + " figure")
    lines = []
    lines.append("<!-- {0} -->".format(p["id"]))
    lines.append('<div class="block">')
    lines.append('  <div class="abstract">')
    lines.append('  <img class="project_img" src="{src}" alt="{alt}">'.format(
        src=p["image"], alt=html.escape(alt, quote=True)))
    lines.append('  <div class="right">')
    lines.append('  <div class="research_title">')
    lines.append('  {0}'.format(p["title"]))
    lines.append('  </div>')
    if p.get("abstract"):
        lines.append('  <p>')
        lines.append('  {0}'.format(p["abstract"].strip()))
        lines.append('  </p>')
    lines.append('  </div>')
    lines.append('  </div>')
    lines.append('  <div class="publication">')
    lines.append('    {0}'.format(render_authors(p["authors"], p.get("note"))))
    lines.append('  <br>')
    lines.append('  {0}<br>'.format(p["pubtitle"]))
    venue_line = '  {0}'.format(p["venue"].strip())
    links = render_links(p.get("links"))
    if links:
        venue_line += "\n  " + links
    lines.append(venue_line)
    if p.get("extra"):
        lines.append('  {0}'.format(p["extra"].strip()))
    lines.append('  </div>')
    lines.append('</div>')
    return "\n".join(lines)


def build_region(papers):
    out = []
    for key, heading, note in SECTIONS:
        group = [p for p in papers if p.get("section") == key]
        out.append('<div class="subtitle">{0}</div>'.format(heading))
        if note:
            out.append(note)
        out.append("")
        for p in group:
            out.append(render_paper(p))
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    with open(YAML_PATH, encoding="utf-8") as f:
        papers = yaml.safe_load(f)
    if not isinstance(papers, list):
        sys.exit("ERROR: papers.yml must be a top-level list of papers.")

    known = {k for k, _, _ in SECTIONS}
    for p in papers:
        if p.get("section") not in known:
            sys.exit("ERROR: paper '{0}' has unknown section '{1}' "
                     "(use one of: {2})".format(
                         p.get("id", "?"), p.get("section"), ", ".join(sorted(known))))

    region = build_region(papers)

    with open(HTML_PATH, encoding="utf-8") as f:
        doc = f.read()

    if START not in doc or END not in doc:
        sys.exit(
            "ERROR: could not find the PAPERS markers in index.html.\n"
            "Expected these two lines somewhere in the file:\n"
            "  {0}\n  {1}".format(START, END))

    pre, rest = doc.split(START, 1)
    _, post = rest.split(END, 1)
    new_doc = pre + START + "\n" + region + END + post

    with open(HTML_PATH, "w", encoding="utf-8") as f:
        f.write(new_doc)

    counts = {}
    for p in papers:
        counts[p["section"]] = counts.get(p["section"], 0) + 1
    summary = ", ".join("{0}: {1}".format(k, counts.get(k, 0))
                        for k, _, _ in SECTIONS)
    print("Wrote {0} papers to index.html ({1}).".format(len(papers), summary))


if __name__ == "__main__":
    main()
